<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::table('countries')->delete();
		$countries = array(
			array('id' => 1,'short_code' => 'AF' ,'name' => "Afghanistan",'phonecode' => 93,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 2,'short_code' => 'AL' ,'name' => "Albania",'phonecode' => 355,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 3,'short_code' => 'DZ' ,'name' => "Algeria",'phonecode' => 213,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 4,'short_code' => 'AS' ,'name' => "American Samoa",'phonecode' => 1684,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 5,'short_code' => 'AD' ,'name' => "Andorra",'phonecode' => 376,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 6,'short_code' => 'AO' ,'name' => "Angola",'phonecode' => 244,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 7,'short_code' => 'AI' ,'name' => "Anguilla",'phonecode' => 1264,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 8,'short_code' => 'AQ' ,'name' => "Antarctica",'phonecode' => 0,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 9,'short_code' => 'AG' ,'name' => "Antigua And Barbuda",'phonecode' => 1268,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 10,'short_code' => 'AR','name' => "Argentina",'phonecode' => 54,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 11,'short_code' => 'AM','name' => "Armenia",'phonecode' => 374,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 12,'short_code' => 'AW','name' => "Aruba",'phonecode' => 297,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 13,'short_code' => 'AU','name' => "Australia",'phonecode' => 61,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 14,'short_code' => 'AT','name' => "Austria",'phonecode' => 43,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 15,'short_code' => 'AZ','name' => "Azerbaijan",'phonecode' => 994,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 16,'short_code' => 'BS','name' => "Bahamas The",'phonecode' => 1242,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 17,'short_code' => 'BH','name' => "Bahrain",'phonecode' => 973,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 18,'short_code' => 'BD','name' => "Bangladesh",'phonecode' => 880,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 19,'short_code' => 'BB','name' => "Barbados",'phonecode' => 1246,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 20,'short_code' => 'BY','name' => "Belarus",'phonecode' => 375,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 21,'short_code' => 'BE','name' => "Belgium",'phonecode' => 32,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 22,'short_code' => 'BZ','name' => "Belize",'phonecode' => 501,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 23,'short_code' => 'BJ','name' => "Benin",'phonecode' => 229,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 24,'short_code' => 'BM','name' => "Bermuda",'phonecode' => 1441,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 25,'short_code' => 'BT','name' => "Bhutan",'phonecode' => 975,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 26,'short_code' => 'BO','name' => "Bolivia",'phonecode' => 591,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 27,'short_code' => 'BA','name' => "Bosnia and Herzegovina",'phonecode' => 387,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 28,'short_code' => 'BW','name' => "Botswana",'phonecode' => 267,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 29,'short_code' => 'BV','name' => "Bouvet Island",'phonecode' => 0,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 30,'short_code' => 'BR','name' => "Brazil",'phonecode' => 55,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 31,'short_code' => 'IO','name' => "British Indian Ocean Territory",'phonecode' => 246,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 32,'short_code' => 'BN','name' => "Brunei",'phonecode' => 673,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 33,'short_code' => 'BG','name' => "Bulgaria",'phonecode' => 359,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 34,'short_code' => 'BF','name' => "Burkina Faso",'phonecode' => 226,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 35,'short_code' => 'BI','name' => "Burundi",'phonecode' => 257,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 36,'short_code' => 'KH','name' => "Cambodia",'phonecode' => 855,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 37,'short_code' => 'CM','name' => "Cameroon",'phonecode' => 237,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 38,'short_code' => 'CA','name' => "Canada",'phonecode' => 1,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 39,'short_code' => 'CV','name' => "Cape Verde",'phonecode' => 238,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 40,'short_code' => 'KY','name' => "Cayman Islands",'phonecode' => 1345,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 41,'short_code' => 'CF','name' => "Central African Republic",'phonecode' => 236,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 42,'short_code' => 'TD','name' => "Chad",'phonecode' => 235,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 43,'short_code' => 'CL','name' => "Chile",'phonecode' => 56,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 44,'short_code' => 'CN','name' => "China",'phonecode' => 86,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 45,'short_code' => 'CX','name' => "Christmas Island",'phonecode' => 61,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 46,'short_code' => 'CC','name' => "Cocos (Keeling) Islands",'phonecode' => 672,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 47,'short_code' => 'CO','name' => "Colombia",'phonecode' => 57,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 48,'short_code' => 'KM','name' => "Comoros",'phonecode' => 269,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 49,'short_code' => 'CG','name' => "Congo",'phonecode' => 242,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 50,'short_code' => 'CD','name' => "Congo The Democratic Republic Of The",'phonecode' => 242,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 51,'short_code' => 'CK','name' => "Cook Islands",'phonecode' => 682,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 52,'short_code' => 'CR','name' => "Costa Rica",'phonecode' => 506,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 53,'short_code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phonecode' => 225,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 54,'short_code' => 'HR','name' => "Croatia (Hrvatska)",'phonecode' => 385,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 55,'short_code' => 'CU','name' => "Cuba",'phonecode' => 53,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 56,'short_code' => 'CY','name' => "Cyprus",'phonecode' => 357,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 57,'short_code' => 'CZ','name' => "Czech Republic",'phonecode' => 420,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 58,'short_code' => 'DK','name' => "Denmark",'phonecode' => 45,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 59,'short_code' => 'DJ','name' => "Djibouti",'phonecode' => 253,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 60,'short_code' => 'DM','name' => "Dominica",'phonecode' => 1767,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 61,'short_code' => 'DO','name' => "Dominican Republic",'phonecode' => 1809,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 62,'short_code' => 'TP','name' => "East Timor",'phonecode' => 670,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 63,'short_code' => 'EC','name' => "Ecuador",'phonecode' => 593,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 64,'short_code' => 'EG','name' => "Egypt",'phonecode' => 20,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 65,'short_code' => 'SV','name' => "El Salvador",'phonecode' => 503,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 66,'short_code' => 'GQ','name' => "Equatorial Guinea",'phonecode' => 240,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 67,'short_code' => 'ER','name' => "Eritrea",'phonecode' => 291,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 68,'short_code' => 'EE','name' => "Estonia",'phonecode' => 372,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 69,'short_code' => 'ET','name' => "Ethiopia",'phonecode' => 251,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 70,'short_code' => 'XA','name' => "External Territories of Australia",'phonecode' => 61,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 71,'short_code' => 'FK','name' => "Falkland Islands",'phonecode' => 500,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 72,'short_code' => 'FO','name' => "Faroe Islands",'phonecode' => 298,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 73,'short_code' => 'FJ','name' => "Fiji Islands",'phonecode' => 679,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 74,'short_code' => 'FI','name' => "Finland",'phonecode' => 358,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 75,'short_code' => 'FR','name' => "France",'phonecode' => 33,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 76,'short_code' => 'GF','name' => "French Guiana",'phonecode' => 594,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 77,'short_code' => 'PF','name' => "French Polynesia",'phonecode' => 689,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 78,'short_code' => 'TF','name' => "French Southern Territories",'phonecode' => 0,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 79,'short_code' => 'GA','name' => "Gabon",'phonecode' => 241,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 80,'short_code' => 'GM','name' => "Gambia The",'phonecode' => 220,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 81,'short_code' => 'GE','name' => "Georgia",'phonecode' => 995,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 82,'short_code' => 'DE','name' => "Germany",'phonecode' => 49,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 83,'short_code' => 'GH','name' => "Ghana",'phonecode' => 233,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 84,'short_code' => 'GI','name' => "Gibraltar",'phonecode' => 350,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 85,'short_code' => 'GR','name' => "Greece",'phonecode' => 30,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 86,'short_code' => 'GL','name' => "Greenland",'phonecode' => 299,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 87,'short_code' => 'GD','name' => "Grenada",'phonecode' => 1473,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 88,'short_code' => 'GP','name' => "Guadeloupe",'phonecode' => 590,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 89,'short_code' => 'GU','name' => "Guam",'phonecode' => 1671,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 90,'short_code' => 'GT','name' => "Guatemala",'phonecode' => 502,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 91,'short_code' => 'XU','name' => "Guernsey and Alderney",'phonecode' => 44,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 92,'short_code' => 'GN','name' => "Guinea",'phonecode' => 224,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 93,'short_code' => 'GW','name' => "Guinea-Bissau",'phonecode' => 245,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 94,'short_code' => 'GY','name' => "Guyana",'phonecode' => 592,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 95,'short_code' => 'HT','name' => "Haiti",'phonecode' => 509,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 96,'short_code' => 'HM','name' => "Heard and McDonald Islands",'phonecode' => 0,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 97,'short_code' => 'HN','name' => "Honduras",'phonecode' => 504,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 98,'short_code' => 'HK','name' => "Hong Kong S.A.R.",'phonecode' => 852,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 99,'short_code' => 'HU','name' => "Hungary",'phonecode' => 36,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 100,'short_code' => 'IS','name' => "Iceland",'phonecode' => 354,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 101,'short_code' => 'IN','name' => "India",'phonecode' => 91,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 102,'short_code' => 'ID','name' => "Indonesia",'phonecode' => 62,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 103,'short_code' => 'IR','name' => "Iran",'phonecode' => 98,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 104,'short_code' => 'IQ','name' => "Iraq",'phonecode' => 964,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 105,'short_code' => 'IE','name' => "Ireland",'phonecode' => 353,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 106,'short_code' => 'IL','name' => "Israel",'phonecode' => 972,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 107,'short_code' => 'IT','name' => "Italy",'phonecode' => 39,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 108,'short_code' => 'JM','name' => "Jamaica",'phonecode' => 1876,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 109,'short_code' => 'JP','name' => "Japan",'phonecode' => 81,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 110,'short_code' => 'XJ','name' => "Jersey",'phonecode' => 44,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 111,'short_code' => 'JO','name' => "Jordan",'phonecode' => 962,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 112,'short_code' => 'KZ','name' => "Kazakhstan",'phonecode' => 7,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 113,'short_code' => 'KE','name' => "Kenya",'phonecode' => 254,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 114,'short_code' => 'KI','name' => "Kiribati",'phonecode' => 686,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 115,'short_code' => 'KP','name' => "Korea North",'phonecode' => 850,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 116,'short_code' => 'KR','name' => "Korea South",'phonecode' => 82,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 117,'short_code' => 'KW','name' => "Kuwait",'phonecode' => 965,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 118,'short_code' => 'KG','name' => "Kyrgyzstan",'phonecode' => 996,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 119,'short_code' => 'LA','name' => "Laos",'phonecode' => 856,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 120,'short_code' => 'LV','name' => "Latvia",'phonecode' => 371,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 121,'short_code' => 'LB','name' => "Lebanon",'phonecode' => 961,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 122,'short_code' => 'LS','name' => "Lesotho",'phonecode' => 266,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 123,'short_code' => 'LR','name' => "Liberia",'phonecode' => 231,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 124,'short_code' => 'LY','name' => "Libya",'phonecode' => 218,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 125,'short_code' => 'LI','name' => "Liechtenstein",'phonecode' => 423,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 126,'short_code' => 'LT','name' => "Lithuania",'phonecode' => 370,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 127,'short_code' => 'LU','name' => "Luxembourg",'phonecode' => 352,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 128,'short_code' => 'MO','name' => "Macau S.A.R.",'phonecode' => 853,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 129,'short_code' => 'MK','name' => "Macedonia",'phonecode' => 389,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 130,'short_code' => 'MG','name' => "Madagascar",'phonecode' => 261,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 131,'short_code' => 'MW','name' => "Malawi",'phonecode' => 265,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 132,'short_code' => 'MY','name' => "Malaysia",'phonecode' => 60,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 133,'short_code' => 'MV','name' => "Maldives",'phonecode' => 960,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 134,'short_code' => 'ML','name' => "Mali",'phonecode' => 223,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 135,'short_code' => 'MT','name' => "Malta",'phonecode' => 356,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 136,'short_code' => 'XM','name' => "Man (Isle of)",'phonecode' => 44,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 137,'short_code' => 'MH','name' => "Marshall Islands",'phonecode' => 692,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 138,'short_code' => 'MQ','name' => "Martinique",'phonecode' => 596,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 139,'short_code' => 'MR','name' => "Mauritania",'phonecode' => 222,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 140,'short_code' => 'MU','name' => "Mauritius",'phonecode' => 230,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 141,'short_code' => 'YT','name' => "Mayotte",'phonecode' => 269,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 142,'short_code' => 'MX','name' => "Mexico",'phonecode' => 52,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 143,'short_code' => 'FM','name' => "Micronesia",'phonecode' => 691,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 144,'short_code' => 'MD','name' => "Moldova",'phonecode' => 373,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 145,'short_code' => 'MC','name' => "Monaco",'phonecode' => 377,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 146,'short_code' => 'MN','name' => "Mongolia",'phonecode' => 976,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 147,'short_code' => 'MS','name' => "Montserrat",'phonecode' => 1664,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 148,'short_code' => 'MA','name' => "Morocco",'phonecode' => 212,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 149,'short_code' => 'MZ','name' => "Mozambique",'phonecode' => 258,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 150,'short_code' => 'MM','name' => "Myanmar",'phonecode' => 95,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 151,'short_code' => 'NA','name' => "Namibia",'phonecode' => 264,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 152,'short_code' => 'NR','name' => "Nauru",'phonecode' => 674,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 153,'short_code' => 'NP','name' => "Nepal",'phonecode' => 977,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 154,'short_code' => 'AN','name' => "Netherlands Antilles",'phonecode' => 599,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 155,'short_code' => 'NL','name' => "Netherlands The",'phonecode' => 31,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 156,'short_code' => 'NC','name' => "New Caledonia",'phonecode' => 687,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 157,'short_code' => 'NZ','name' => "New Zealand",'phonecode' => 64,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 158,'short_code' => 'NI','name' => "Nicaragua",'phonecode' => 505,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 159,'short_code' => 'NE','name' => "Niger",'phonecode' => 227,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 160,'short_code' => 'NG','name' => "Nigeria",'phonecode' => 234,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 161,'short_code' => 'NU','name' => "Niue",'phonecode' => 683,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 162,'short_code' => 'NF','name' => "Norfolk Island",'phonecode' => 672,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 163,'short_code' => 'MP','name' => "Northern Mariana Islands",'phonecode' => 1670,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 164,'short_code' => 'NO','name' => "Norway",'phonecode' => 47,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 165,'short_code' => 'OM','name' => "Oman",'phonecode' => 968,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 166,'short_code' => 'PK','name' => "Pakistan",'phonecode' => 92,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 167,'short_code' => 'PW','name' => "Palau",'phonecode' => 680,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 168,'short_code' => 'PS','name' => "Palestinian Territory Occupied",'phonecode' => 970,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 169,'short_code' => 'PA','name' => "Panama",'phonecode' => 507,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 170,'short_code' => 'PG','name' => "Papua new Guinea",'phonecode' => 675,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 171,'short_code' => 'PY','name' => "Paraguay",'phonecode' => 595,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 172,'short_code' => 'PE','name' => "Peru",'phonecode' => 51,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 173,'short_code' => 'PH','name' => "Philippines",'phonecode' => 63,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 174,'short_code' => 'PN','name' => "Pitcairn Island",'phonecode' => 0,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 175,'short_code' => 'PL','name' => "Poland",'phonecode' => 48,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 176,'short_code' => 'PT','name' => "Portugal",'phonecode' => 351,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 177,'short_code' => 'PR','name' => "Puerto Rico",'phonecode' => 1787,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 178,'short_code' => 'QA','name' => "Qatar",'phonecode' => 974,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 179,'short_code' => 'RE','name' => "Reunion",'phonecode' => 262,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 180,'short_code' => 'RO','name' => "Romania",'phonecode' => 40,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 181,'short_code' => 'RU','name' => "Russia",'phonecode' => 70,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 182,'short_code' => 'RW','name' => "Rwanda",'phonecode' => 250,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 183,'short_code' => 'SH','name' => "Saint Helena",'phonecode' => 290,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 184,'short_code' => 'KN','name' => "Saint Kitts And Nevis",'phonecode' => 1869,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 185,'short_code' => 'LC','name' => "Saint Lucia",'phonecode' => 1758,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 186,'short_code' => 'PM','name' => "Saint Pierre and Miquelon",'phonecode' => 508,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 187,'short_code' => 'VC','name' => "Saint Vincent And The Grenadines",'phonecode' => 1784,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 188,'short_code' => 'WS','name' => "Samoa",'phonecode' => 684,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 189,'short_code' => 'SM','name' => "San Marino",'phonecode' => 378,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 190,'short_code' => 'ST','name' => "Sao Tome and Principe",'phonecode' => 239,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 191,'short_code' => 'SA','name' => "Saudi Arabia",'phonecode' => 966,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 192,'short_code' => 'SN','name' => "Senegal",'phonecode' => 221,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 193,'short_code' => 'RS','name' => "Serbia",'phonecode' => 381,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 194,'short_code' => 'SC','name' => "Seychelles",'phonecode' => 248,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 195,'short_code' => 'SL','name' => "Sierra Leone",'phonecode' => 232,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 196,'short_code' => 'SG','name' => "Singapore",'phonecode' => 65,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 197,'short_code' => 'SK','name' => "Slovakia",'phonecode' => 421,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 198,'short_code' => 'SI','name' => "Slovenia",'phonecode' => 386,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 199,'short_code' => 'XG','name' => "Smaller Territories of the UK",'phonecode' => 44,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 200,'short_code' => 'SB','name' => "Solomon Islands",'phonecode' => 677,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 201,'short_code' => 'SO','name' => "Somalia",'phonecode' => 252,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 202,'short_code' => 'ZA','name' => "South Africa",'phonecode' => 27,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 203,'short_code' => 'GS','name' => "South Georgia",'phonecode' => 0,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 204,'short_code' => 'SS','name' => "South Sudan",'phonecode' => 211,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 205,'short_code' => 'ES','name' => "Spain",'phonecode' => 34,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 206,'short_code' => 'LK','name' => "Sri Lanka",'phonecode' => 94,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 207,'short_code' => 'SD','name' => "Sudan",'phonecode' => 249,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 208,'short_code' => 'SR','name' => "Suriname",'phonecode' => 597,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 209,'short_code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phonecode' => 47,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 210,'short_code' => 'SZ','name' => "Swaziland",'phonecode' => 268,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 211,'short_code' => 'SE','name' => "Sweden",'phonecode' => 46,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 212,'short_code' => 'CH','name' => "Switzerland",'phonecode' => 41,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 213,'short_code' => 'SY','name' => "Syria",'phonecode' => 963,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 214,'short_code' => 'TW','name' => "Taiwan",'phonecode' => 886,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 215,'short_code' => 'TJ','name' => "Tajikistan",'phonecode' => 992,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 216,'short_code' => 'TZ','name' => "Tanzania",'phonecode' => 255,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 217,'short_code' => 'TH','name' => "Thailand",'phonecode' => 66,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 218,'short_code' => 'TG','name' => "Togo",'phonecode' => 228,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 219,'short_code' => 'TK','name' => "Tokelau",'phonecode' => 690,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 220,'short_code' => 'TO','name' => "Tonga",'phonecode' => 676,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 221,'short_code' => 'TT','name' => "Trinidad And Tobago",'phonecode' => 1868,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 222,'short_code' => 'TN','name' => "Tunisia",'phonecode' => 216,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 223,'short_code' => 'TR','name' => "Turkey",'phonecode' => 90,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 224,'short_code' => 'TM','name' => "Turkmenistan",'phonecode' => 7370,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 225,'short_code' => 'TC','name' => "Turks And Caicos Islands",'phonecode' => 1649,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 226,'short_code' => 'TV','name' => "Tuvalu",'phonecode' => 688,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 227,'short_code' => 'UG','name' => "Uganda",'phonecode' => 256,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 228,'short_code' => 'UA','name' => "Ukraine",'phonecode' => 380,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 229,'short_code' => 'AE','name' => "United Arab Emirates",'phonecode' => 971,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 230,'short_code' => 'GB','name' => "United Kingdom",'phonecode' => 44,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 231,'short_code' => 'US','name' => "United States",'phonecode' => 1,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 232,'short_code' => 'UM','name' => "United States Minor Outlying Islands",'phonecode' => 1,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 233,'short_code' => 'UY','name' => "Uruguay",'phonecode' => 598,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 234,'short_code' => 'UZ','name' => "Uzbekistan",'phonecode' => 998,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 235,'short_code' => 'VU','name' => "Vanuatu",'phonecode' => 678,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 236,'short_code' => 'VA','name' => "Vatican City State (Holy See)",'phonecode' => 39,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 237,'short_code' => 'VE','name' => "Venezuela",'phonecode' => 58,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 238,'short_code' => 'VN','name' => "Vietnam",'phonecode' => 84,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 239,'short_code' => 'VG','name' => "Virgin Islands (British)",'phonecode' => 1284,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 240,'short_code' => 'VI','name' => "Virgin Islands (US)",'phonecode' => 1340,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 241,'short_code' => 'WF','name' => "Wallis And Futuna Islands",'phonecode' => 681,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 242,'short_code' => 'EH','name' => "Western Sahara",'phonecode' => 212,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 243,'short_code' => 'YE','name' => "Yemen",'phonecode' => 967,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 244,'short_code' => 'YU','name' => "Yugoslavia",'phonecode' => 38,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 245,'short_code' => 'ZM','name' => "Zambia",'phonecode' => 260,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
			array('id' => 246,'short_code' => 'ZW','name' => "Zimbabwe",'phonecode' => 263,'status' =>1,'created_at' => date('Y-m-d H:i:s')),
		);
		DB::table('countries')->insert($countries);
    }
}
